name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      _github_token: secrets.GITHUB_TOKEN

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=0.0.1-pre$GITHUB_RUN_NUMBER
    - name: Test
      run: dotnet test --no-build --no-restore --configuration Release --no-restore /p:Version=0.0.1-pre$GITHUB_RUN_NUMBER
    - if: env._github_token != ''
      name: Publish
      run: find . -name $projectName\*.nupkg -print -exec dotnet nuget push -s https://nuget.pkg.github.com/CombinationAB/index.json -k ${{ secrets.GITHUB_TOKEN }} {} \;
